### ISSUE TITLE
What are the data points required for just inference?

### ISSUE THREAD

**Issue by DataEnthusiastSathya** [guanyingc/SDPS-Net#1]
Thanks a lot for the code and an amazing paper.
I have a data set of images which are taken under different lightning directions but same camera position. But I don't have light directions or any other information. So how should I handle this?

**Comment by guanyingc** [comment]
Hi, just came back from the holiday and sorry for the late reply.
I suggests you to organize your dataset in a form similar to DiLiGenT benchmark and change the path to your dataset. You can just simply set the ground-truth light directions and normals to some random values, as those values will not affect the estimation of our method.

**Comment by DataEnthusiastSathya** [comment]
Thanks a lot for your reply. I was trying to do that anyways.

**Comment by yutoumanman** [comment]
ｉ want to ask the question that is if i use 10 photos ,how can  test?

**Comment by guanyingc** [comment]
Please refer to the updated README and `UPS_Custom_Dataset.py` to test your own dataset.
