### ISSUE TITLE
Question about format of dataset

### ISSUE THREAD

**Issue by xpirad** [guanyingc/SDPS-Net#10]
Hi, i've got some questions about the PS dataset. Can you help me?
![image](https://user-images.githubusercontent.com/24430064/83347501-f8361e80-a357-11ea-909c-b42c59565423.png)
For example, in the PS Blobby Dataset, we've got blob01_s-0.06_x-000_y-000_two-layer-gold.txt.
What does its contents mean, like?
![image](https://user-images.githubusercontent.com/24430064/83347518-169c1a00-a358-11ea-8ed8-2e8ed13a5f70.png)
What are the meaning of these numbers?

Also, if i read the code correct, the image intensity is generated randomly during runtime? Is my understanding correct?  (In the pms_tranforms.py?)
![image](https://user-images.githubusercontent.com/24430064/83347545-4c410300-a358-11ea-959d-98622b1cbca3.png)

Thanks!

**Comment by guanyingc** [comment]
Hi,
1.  The first column is the name of the image, the second to fourth columns indicate the 3d-vector light direction (x,y,z).
2. Yes, light intensities are randomly generated at run time.

**Comment by xpirad** [comment]
Thanks for the quick reply!
1. What does the number in the name of image imply? It has three numbers?
2. But what are the real light intensities? Is it okay to do this?

**Comment by guanyingc** [comment]
1. In fact, the three number in the name are just the 3d-vector light direction, but with '%.2f' precision.
2. During rendering, the light intensity are set 1 for all images. Basically, according to the image formation model, light intensity only affects the scale of the image. It should be okay to do this.

**Comment by xpirad** [comment]
Now i understand! Thank you! Very nice explanation.
