### ISSUE TITLE
Download problem：sh scripts/prepare_diligent_dataset.sh

### ISSUE THREAD

**Issue by zhouguang0** [guanyingc/SDPS-Net#13]
正在解析主机 www.dropbox.com (www.dropbox.com)... 失败：未知的名称或服务。
wget: 无法解析主机地址 “www.dropbox.com”

**Comment by guanyingc** [comment]
Hi, please download the DiLiGenT Dataset in https://sites.google.com/site/photometricstereodata/single?authuser=0
