### ISSUE TITLE
Test SDPS-Net on myself dataset

### ISSUE THREAD

**Issue by zhouguang0** [guanyingc/SDPS-Net#14]
If I want to implement myself Dataset class, Do I have to have a light calibration picture？For example, your Dataset class have the data/ToyPSDataset/Bunny and  data/ToyPSDataset/Sphere , but my Dataset class only have data/ToyPSDataset/Bunny， no have data/ToyPSDataset/Sphere， So can I still use your SDPS-Net test?

**Comment by guanyingc** [comment]
Hi, you don't need to have the light calibration picture. In fact, Bunny and sphere are two independent testing example. We only use the sphere for testing, not for lighting calibration.

**Comment by zhouguang0** [comment]
Oh!&nbsp;Thank you for your answer,&nbsp;because I see too many light calibration with spheres, so it may lead me to think of one.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guanyingc/SDPS-Net"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月20日(星期三) 上午10:13
收件人:&nbsp;"guanyingc/SDPS-Net"<SDPS-Net@noreply.github.com&gt;;
抄送:&nbsp;"做你的Angel"<805440175@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guanyingc/SDPS-Net] Test SDPS-Net on myself dataset (#14)





 
Hi, you don't need to have the light calibration picture. In fact, Bunny and sphere are two independent testing example. We only use the sphere for testing, not for lighting calibration.
