### ISSUE TITLE
Data capturing setup and number of light source

### ISSUE THREAD

**Issue by zombicore** [guanyingc/SDPS-Net#15]
hello 1- how does the setup looks like ?
2- how many light sources i need ? 
3- can i make the light colored ? for example red blue green white ? 
4- how many images do i need to take to make 3D object ?

**Comment by guanyingc** [comment]
Hi,

1. For the data capturing, please refer to the DiLiGenT paper: https://sites.google.com/site/photometricstereodata/single?authuser=0.

2. Normally our method requires around 8 light sources to produce robust results.
3. This paper only consider white direction light source. You may search other related papers.
4. Please note that our method only recover the surface normal map from a single view.

**Comment by zombicore** [comment]
Hi 
the URL doesnt let me read its content ( We are sorry, but you do not have access to this service. Please contact your Organization Administrator for access  ) 
you mentioned "Please note that our method only recover the surface normal map from a single view."  do you means that if i scanned the front view , it only show normals of one that view ?  and if i need to make 360 i need to make other scans then do alignment ? 
does the system use CUDA for GPU processing ?

**Comment by guanyingc** [comment]
Hi, 

1. Please read "A Benchmark Dataset and Evaluation for Non-Lambertian and Uncalibrated Photometric Stereo, TPAMI2020" for a practical setup.

2. Yes, if you scan the front view, our method only recover the normals for that view.

3. This method can be ran in both CPU and GPU mode. https://github.com/guanyingc/SDPS-Net#q3-could-i-run-your-code-only-using-cpus

**Comment by zombicore** [comment]
Hi
thank you a lot for fast reply 
i found that should use in the setup industrial camera , in the PDF they mention specific model ,
 does that means the system already control the camera to take shots ? or/  i put the input images and it process the ply , kindly correct me 

do i need Matlab software for this process ?

**Comment by guanyingc** [comment]
Hi, 

1. Please note that this code does not take care of the data capturing part. 
2. It can only recover the normals for image captured from a single viewpoint. You have to take care of multi-view processing and alignment by yourself.

**Comment by zombicore** [comment]
Hi 
one more thing i need to know , do i need Matlab software in any kind of processing ?

**Comment by guanyingc** [comment]
Using this code for normal estimation, we don't need Matlab for processing.
