### ISSUE TITLE
A problem about color_aug and int_aug

### ISSUE THREAD

**Issue by HandsomeHehe** [guanyingc/SDPS-Net#17]
Hi, Guanying! Thanks for your code. 
I'm little confused about function of next two code:
`  if self.args.color_aug:
            img = (img * np.random.uniform(1, 3))`
` if self.args.int_aug:
            ints = pms_transforms.getIntensity(len(imgs))
            img  = np.dot(img, np.diag(ints.reshape(-1)))`

**Comment by guanyingc** [comment]
Hi,
1. --color_aug is used to multiple all the input image with the same randomly scalar. This is for data augmentation purpose.
2. --int_aug is used to simulate input images captured with different light intensities. Different images will be multiplied by different scalars.

**Comment by HandsomeHehe** [comment]
Thank you for your reply!
If I consider pixel value saturation. Would I add the clip at the end of the `np.dot(img,` `np.diag(ints.reshape(-1))`. 
Like this:
`        if self.args.int_aug:
            ints =  pms_transforms.getIntensity(len(imgs))
            img  = (np.dot(img, np.diag(ints.reshape(-1))).clip(0,1)`
