### ISSUE TITLE
Download problem: sh ./scripts/download_pretrained_models.sh

### ISSUE THREAD

**Issue by Banhalmi** [guanyingc/SDPS-Net#19]
waiting response... 503 Service Unavailable

**Comment by guanyingc** [comment]
Sorry for that our server is down. Please donwload the models from https://drive.google.com/drive/folders/1HCW9YDfsFoPxda3GDTjj3L5yuQUXw8a3 as suggested.
![image](https://user-images.githubusercontent.com/8651158/164233568-371de3e5-1b51-4e61-a259-eb059b92bd83.png)
