### ISSUE TITLE
3d reconstruction

### ISSUE THREAD

**Issue by DataEnthusiastSathya** [guanyingc/SDPS-Net#2]
Hi, Thanks a lot for the code. 
Is there a way to construct the 3d structure from the normal maps?

**Comment by guanyingc** [comment]
Hi, you can use some existing normal integration methods to get the depth map from normal map.

**Comment by DataEnthusiastSathya** [comment]
Thanks for the tip. any suggested method ?
I'm looking at Frankot Chellapa algorithm, SSD-C, etc..

**Comment by guanyingc** [comment]
You may use the code provided in http://vision.seas.harvard.edu/qsfs/Data.html .

**Comment by DataEnthusiastSathya** [comment]
Thanks again Chen. Your paper and code is so well organized and amazing.

**Comment by DataEnthusiastSathya** [comment]
Hi, I'm trying to implement the algorithm mentioned by using the surface normal map created, but I'm not able to get the results. Can you help me with the approach that has to be used here.

**Comment by guanyingc** [comment]
Hi, I am not sure about your problem. Maybe you need to figure it out by yourself as this repo only focuses on the normal estimation part. Thank you for your interests and understanding.
