### ISSUE TITLE
About Breakpoint Training

### ISSUE THREAD

**Issue by wrs-code** [guanyingc/SDPS-Net#21]
Hi author, I tried to train the model with your code, but the training was interrupted halfway, how should I continue the training?

**Comment by wrs-code** [comment]
Addendum: I am training the stage2 model

**Comment by guanyingc** [comment]
Hi, you might try
```
CUDA_VISIBLE_DEVICES=0 python main_stage2.py --in_img_num 32 --retrain data/logdir/path/to/checkpointDirOfLCNet/checkpoint20.pth.tar --retrain_s2 /path/to/your/half-trained-stage2-mode.pth.tar
``` 
You might need to adjust the initial learning rate as well.

**Comment by wrs-code** [comment]
> Hi, you might try
> 
> ```
> CUDA_VISIBLE_DEVICES=0 python main_stage2.py --in_img_num 32 --retrain data/logdir/path/to/checkpointDirOfLCNet/checkpoint20.pth.tar --retrain_s2 /path/to/your/half-trained-stage2-mode.pth.tar
> ```
> 
> You might need to adjust the initial learning rate as well.

Thank you very much for your reply！That's very helpful.
