### ISSUE TITLE
Light directions

### ISSUE THREAD

**Issue by ahuilove** [guanyingc/SDPS-Net#24]
Hi! I am wondering how to get the light directions.Is this three-dimensional vector obtained based on the camera position？What is this coordinate system like，such as its origin of coordinates，axis x , axis y ,axis z.

**Comment by guanyingc** [comment]
Hi, please check https://github.com/guanyingc/PS-FCN/issues/21.

**Comment by ahuilove** [comment]
Thank you for the reply!
