### ISSUE TITLE
Training: cannot find checkpoint20.pth.tar

### ISSUE THREAD

**Issue by foamposite** [guanyingc/SDPS-Net#27]
Dear professor
I'm following the tutorial to train the model on the PS Blobby and Sculpture datasets. But after finishing the stage1 training process, I cannot find the exact directory or file used for stage2 training （data/logdir/path/to/checkpointDirOfLCNet/checkpoint20.pth.tar）
But files chechp_20.pth.tar and checkp_20._res.pth.tar can be found in subdirectory of data/logdir. Should i take one of these files to replace the "--retrain" parameter path and which one if right?

**Comment by guanyingc** [comment]
Yes.

**Comment by foamposite** [comment]
thanks
