### ISSUE TITLE
Error with ToyPSDataset

### ISSUE THREAD

**Issue by fengpingxuan** [guanyingc/SDPS-Net#3]
Hello,

Thanks for sharing the code of this excellent research work.

I followed the ReadMe to setup the environment, and I can successfully run the tests on the DiLiGenT dataset. However, when I tried to test SDPS-Net on the ToyPSDataset by runing:

"CUDA_VISIBLE_DEVICES=0 python eval/run_stage2.py --retrain data/models/LCNet_CVPR2019.pth.tar --retrain_s2 data/models/NENet_CVPR2019.pth.tar --benchmark UPS_Custom_Dataset --bm_dir data/ToyPSDataset/"

Errors occured as follows:

------------ Options -------------
        benchmark: UPS_Custom_Dataset
        bm_dir: data/ToyPSDataset/
        bool_keys: ['int_aug', 'test_resc']
        color_aug: True
        color_ratio: 3
        concat_data: True
        crop: True
        crop_h: 128
        crop_w: 128
        cuda: False
        data_dir: data/datasets/PS_Blobby_Dataset
        data_dir2: data/datasets/PS_Sculpture_Dataset
        dataset: UPS_Synth_Dataset
        debug: False
        dir_int: False
        dirs_cls: 36
        epochs: 1
        fuse_type: max
        have_gt_n: False
        have_l_dirs: False
        have_l_ints: False
        in_img_num: 32
        in_light: False
        in_mask: True
        int_aug: True
        ints_cls: 20
        item: CVPR2019
        l_suffix: _mtrl.txt
        log: <utils.logger.Logger object at 0x7f11e8afe150>
        log_dir: data/models/10-25_run_model,LCNet_CVPR2019,LCNet,NENet,UPS_Custom_Dataset,max,in_m-32,te_h-128,te_w-128,int_aug
        make_dir: True
        max_test_iter: -1
        max_train_iter: -1
        max_val_iter: -1
        model: LCNet
        model_s2: NENet
        multi_gpu: False
        noise: 0.05
        noise_aug: True
        normalize: False
        rand_sc: True
        rescale: True
        resume: None
        retrain: data/models/LCNet_CVPR2019.pth.tar
        retrain_s2: data/models/NENet_CVPR2019.pth.tar
        run_model: True
        s1_est_d: True
        s1_est_i: True
        s1_est_n: False
        s2_est_d: False
        s2_est_i: False
        s2_est_n: True
        s2_in_light: True
        save_intv: 1
        save_root: data/logdir/
        save_split: False
        scale_h: 128
        scale_w: 128
        seed: 0
        stage2: True
        str_keys: ['model', 'model_s2', 'benchmark', 'fuse_type']
        suffix: None
        test_batch: 1
        test_disp: 1
        test_h: 128
        test_resc: False
        test_save: 1
        test_save_n: 4
        test_w: 128
        time_sync: False
        train_disp: 20
        train_save: 200
        train_save_n: 4
        use_BN: False
        val_disp: 1
        val_intv: 1
        val_keys: ['in_img_num', 'test_h', 'test_w']
        val_save: 1
        workers: 8
-------------- End ----------------

=> fetching img pairs in 'data/UPS_Custom_Dataset'
[test Data]     2 objs. Root: data/ToyPSDataset/
Found Benchmark Data: 2 samples
         Test Batch 1
Creating Model LCNet
[Network Input] Color image as input
[Network Input] Adding Mask as input
[Network Input] Input channel: 4
=> using pre-trained model 'data/models/LCNet_CVPR2019.pth.tar'
LCNet(
  (featExtractor): FeatExtractor(
    (conv1): Sequential(
      (0): Conv2d(4, 64, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv2): Sequential(
      (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv3): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv4): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv5): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv6): Sequential(
      (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv7): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
  )
  (classifier): Classifier(
    (conv1): Sequential(
      (0): Conv2d(512, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv2): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv3): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv4): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (dir_x_est): Sequential(
      (0): Sequential(
        (0): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
        (1): LeakyReLU(negative_slope=0.1, inplace)
      )
      (1): Sequential(
        (0): Conv2d(64, 36, kernel_size=(1, 1), stride=(1, 1))
      )
    )
    (dir_y_est): Sequential(
      (0): Sequential(
        (0): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
        (1): LeakyReLU(negative_slope=0.1, inplace)
      )
      (1): Sequential(
        (0): Conv2d(64, 36, kernel_size=(1, 1), stride=(1, 1))
      )
    )
    (int_est): Sequential(
      (0): Sequential(
        (0): Conv2d(256, 64, kernel_size=(1, 1), stride=(1, 1))
        (1): LeakyReLU(negative_slope=0.1, inplace)
      )
      (1): Sequential(
        (0): Conv2d(64, 20, kernel_size=(1, 1), stride=(1, 1))
      )
    )
  )
)
=> Model Parameters: 4409692
Creating Stage2 Model NENet
=> using pre-trained model_s2 'data/models/NENet_CVPR2019.pth.tar'
NENet(
  (extractor): FeatExtractor(
    (conv1): Sequential(
      (0): Conv2d(6, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv2): Sequential(
      (0): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv3): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv4): Sequential(
      (0): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv5): Sequential(
      (0): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv6): Sequential(
      (0): ConvTranspose2d(256, 128, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (conv7): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
  )
  (regressor): Regressor(
    (deconv1): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (deconv2): Sequential(
      (0): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (deconv3): Sequential(
      (0): ConvTranspose2d(128, 64, kernel_size=(4, 4), stride=(2, 2), padding=(1, 1), bias=False)
      (1): LeakyReLU(negative_slope=0.1, inplace)
    )
    (est_normal): Sequential(
      (0): Conv2d(64, 3, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    )
  )
)
=> Stage2 Model Parameters: 2210048
---- Start test Epoch 1: 2 batches ----
Rescaling images: from 256X256 to 128X128
/home/seki/.pyenv/versions/anaconda3-5.2.0/envs/sdps-net/lib/python3.7/site-packages/torch/nn/functional.py:2457: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/seki/.pyenv/versions/anaconda3-5.2.0/envs/sdps-net/lib/python3.7/site-packages/torch/nn/functional.py:2539: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))

Intel MKL ERROR: Parameter 7 was incorrect on entry to SGELS.
Traceback (most recent call last):
  File "eval/run_stage2.py", line 28, in <module>
    main(args)
  File "eval/run_stage2.py", line 23, in main
    test_utils.test(args, 'test', test_loader, models, log, 1, recorder)
  File "./test_stage2.py", line 33, in test
    recoder, iter_res, error = prepareRes(args, data, pred_c, pred, recorder, log, split)
  File "./test_stage2.py", line 69, in prepareRes
    int_acc, data['int_err'] = eval_utils.calIntsAcc(data['ints'].data, pred_c['intens'].data, data_batch)
  File "./utils/eval_utils.py", line 26, in calIntsAcc
    scale = torch.gels(gt_i.view(-1, 1), pred_i.view(-1, 1))
RuntimeError: Lapack Error in gels : Illegal Argument 7 at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/TH/generic/THTensorLapack.cpp:165

Would you please tell me what could possibly be the problem and how I can fix it?
Thanks in advance!

**Comment by guanyingc** [comment]
Hi, thanks for your interests.

 It seems the error was caused by the "torch.gels" function which takes "gt_i" and "pred_i" as input.
After checking the code, I think it might be caused by the fact the "gt_i" in UPS_Custom_Dataset is unknown and simply set as 0 in default. Although I cannot reproduce your error I think is should be the reason. You can set the default intensity to 1 referring to my latest commit.

**Comment by fengpingxuan** [comment]
Thanks very much for the update. It works perfectly now.
