### ISSUE TITLE
[Windows system] Problem on running Test : No such file error . 

### ISSUE THREAD

**Issue by bboymoonchild** [guanyingc/SDPS-Net#4]
Hello. 
I want to use/test your model but I encountered following error message: 

(venv) C:\Users\MooNChilD\PycharmProjects\tensorflow prj\SDPS-Net\SDPS-Net>python eval/run_stage2.py --retrain data/models/LCNet_CVPR2019.pth.tar --retrain_s2 data/models/NENet_CVPR2019.pth.tar --benchmark UPS_Custom_Dataset --bm_dir d
ata/ToyPSDataset/
Traceback (most recent call last):
  File "eval/run_stage2.py", line 14, in <module>
    log  = logger.Logger(args)
  File ".\utils\logger.py", line 20, in __init__
    self._setupDirs(args)
  File ".\utils\logger.py", line 54, in _setupDirs
    self.log_fie = open(file_dir, 'w')
**FileNotFoundError: [Errno 2] No such file or directory: 'data/models\\11-5_run_model,LCNet_CVPR2019,LCNet,NENet,UPS_Custom_Dataset,max,in_m-32,te_h-128,te_w-128,int_aug\\11-5_run_model,LCNet_CVPR2019,LCNet,NENet,UPS_Custom_Dataset,max,
in_m-32,te_h-128,te_w-128,int_aug,03:09:27'**

I think I cloned your code well, downloaded all imports and your pretrained net needed, but still doesnt work well. 

Please reply this and thank you very much .

**Comment by guanyingc** [comment]
Hi,

It seems that this error is caused by the logger when it tries to create the log file. The log file path seems problematic (data/model\xxxx). Not sure if this is because of the windows system environment. By the way, can you test our model on DiLiGenT benchmark?

**Comment by bboymoonchild** [comment]
> Hi,
> 
> It seems that this error is caused by the logger when it tries to create the log file. The log file path seems problematic (data/model\xxxx). Not sure if this is because of the windows system environment. By the way, can you test our model on DiLiGenT benchmark?

Im afraid that it shows the same error. Maybe it is because my PyCharm environment does not support sh scripts command, so I downloaded the dataset by myself. Can you please teach me how the file link be when I run sh scripts successfully ?

**Comment by guanyingc** [comment]
sh scripts should be ran in shell. I think it is okay to download the dataset by yourself. Just make sure that the downloaded datasets are located in data/datasets/, the pre-trained models are located in data/models/. I still think it is the problem of different path names between Windows and Linux. Could you also try the training command?

**Comment by bboymoonchild** [comment]
I somehow managed my problem and made shell scripts to be run and found another problem. 

**scripts/prepare_diligent_dataset.sh: line 8: wget: command not found
unzip:  cannot find or open DiLiGenT.zip, DiLiGenT.zip.zip or DiLiGenT.zip.ZIP.
rm: cannot remove 'DiLiGenT.zip': No such file or directory
scripts/prepare_diligent_dataset.sh: line 12: cd: DiLiGenT/pmsData/: No such file or directory
cp: cannot stat 'ballPNG/filenames.txt': No such file or directory
cp: cannot stat 'scripts/DiLiGenT_objects.txt': No such file or directory
E:\DLPrj\venv\Scripts\python.exe: can't open file 'scripts/cropDiLiGenTData.py': [Errno 2] No such file or directory**

It seems that wget script does not work, or the file is deleted from the web you suggested. 

And to run the training command, I got another error message: 
**Downloading PS_Sculpture_Dataset.tgz
scripts/download_synthetic_datasets.sh: line 7: wget: command not found
tar: PS_Sculpture_Dataset.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove 'PS_Sculpture_Dataset.tgz': No such file or directory
Downloading PS_Blobby_Dataset.tgz
scripts/download_synthetic_datasets.sh: line 7: wget: command not found
tar: PS_Blobby_Dataset.tgz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove 'PS_Blobby_Dataset.tgz': No such file or directory**

Please notice this post and reply. 
Thank you very much

**Comment by fengpingxuan** [comment]
Your environment doesn't support wget command, so you may as well download the files and manage them manually instead of using the provided scripts. However, even if you could build up the proper file structure you may still fail in running the program due to some problem caused by the windows system (for which I haven't figured out a solution).

My suggestion is to simply work on a machine with Linux system. If that is not available, you can easily install a WSL([Windows Subsystem for Linux](https://linuxhint.com/install_ubuntu_windows_10_wsl/)) and it should also work. I have tested the SDPS-Net code on WSL Ubuntu and everything runs smoothly. The only problem is that WSL doesn't support CUDA yet so you can only run the processing with CPU. The time cost is somehow acceptable if you don't need to train your own model.

**Comment by bboymoonchild** [comment]
Oh. Thank you for your reply. I still cannot run the code on my PC with the same error with my second post. I think I should study your network more and find other breakthroughs. Thank you for your help .

**Comment by guanyingc** [comment]
Hi, fengpingxuan,

Thank you for your explanation! I agree it is easier to run the code in Linux system. In fact, I haven't tested my code in Windows environment.

**Comment by girigiri2233** [comment]
Hello, I also encountered this problem, I tried to retrain the author's model in windows, but I also encountered the same problem as you, although I can find the file in explorer and the path is not wrong, but I just can't find the file. Did you solve this problem afterwards? If you can reply that would be great!

**Comment by wrs-code** [comment]
> Oh. Thank you for your reply. I still cannot run the code on my PC with the same error with my second post. I think I should study your network more and find other breakthroughs. Thank you for your help .

Hello, I also encountered this problem, I tried to retrain the author's model in windows, but I also encountered the same problem as you, although I can find the file in explorer and the path is not wrong, but I just can't find the file. Did you solve this problem afterwards? If you can reply that would be great!
