### ISSUE TITLE
[Question] Some question about the meaning of output

### ISSUE THREAD

**Issue by xpirad** [guanyingc/SDPS-Net#5]
Hi! I've got some questions, can you help me out? Thanks!!!

![image](https://user-images.githubusercontent.com/24430064/72568301-ce251800-38f2-11ea-9080-c6afbfd5cb20.png)

I tried running the code, but i'm not sure what this int ratio mean(tt_ints_ratio)?

![image](https://user-images.githubusercontent.com/24430064/72568417-12181d00-38f3-11ea-95da-690012476cdc.png)

Also, what is the blu-ish thing in the last part?

Can you shed some light on me, thanks!

**Comment by guanyingc** [comment]
Hi,

Sorry for the confusing outputs. The following are some explanations.

- tt indicates test
- acc indicates accuracy:  tt_n_acc_11 is the percentage of the estimated normals that have an angular error of less than 11 degree. Similarly, 30 and 45 means 30 and 45 degree.
- err indicates error: tt_l_err_mean is the mean angular error for light direction estimation, tt_n_err_mean is the mean angular error for normal estimation
- ratio indicates relative error (i.e., ratio). tt_ints_ratio is the relative error of the estimated light intensity.
- The blue map is the error map of the estimated normal.

Hope this helps! You can refer to the code to further understand the meaning of and how we compute the outputs.

**Comment by xpirad** [comment]
Cool!
Thanks for your detailed explanation!
