### ISSUE TITLE
Results for ToyDataset

### ISSUE THREAD

**Issue by vinayak-pathak** [guanyingc/SDPS-Net#7]
Hi, 
I tested for the ToyDataset using the code
CUDA_VISIBLE_DEVICES=0 python eval/run_stage2.py --retrain data/models/LCNet_CVPR2019.pth.tar --retrain_s2 data/models/NENet_CVPR2019.pth.tar --benchmark UPS_Custom_Dataset --bm_dir data/ToyPSDataset/
as shown on the webpage. 

Where do I locate the final output picture of the model for bunny and sphere.?

**Comment by vinayak-pathak** [comment]
Hi, 
The final outputs can be located in the section Model>2-21_run_model,LCNet_CVPR2019,LCNet,NENet,UPS_Custom_Dataset,max,in_m-32,te_h-128,te_w-128,int_aug>test>Images however I am not sure if there is a way to access just the normal maps.

**Comment by guanyingc** [comment]
Hi, currently we save the input, mask and estimated normals to the output. If you just want to access the normal maps, you can refer to Line 85 at test_stage2.py. Thanks.
https://github.com/guanyingc/SDPS-Net/blob/8775664d6d0592ba93ef16fb0909d90cde2b6c2a/test_stage2.py#L85
