### ISSUE TITLE
Questions about Diligent dataset

### ISSUE THREAD

**Issue by bboymoonchild** [guanyingc/SDPS-Net#9]
Hello. 
I am using your networks to my research and I have a question. is Diligent dataset images so dark just like the image I put ? I am having difficulty of using the image because of the difference of brightness between  the images i have and what i saw from your paper.  

![vrewa](https://user-images.githubusercontent.com/57367997/82315601-7ca6aa00-9a06-11ea-8d11-26ad756914e8.JPG)
![vw](https://user-images.githubusercontent.com/57367997/82315738-b677b080-9a06-11ea-89dc-ca6988316c3a.JPG)

Since the Diligent dataset maker did not make any reply mail to me so I made a question here.
If there is something that I missed while handling the dataset please teach me what it is and thank you very much.

**Comment by guanyingc** [comment]
Hi, the figures showed in the paper are gamma adjusted only for visualization purpose. The images in the DiLiGenT Dataset are 16 bit linear images, such that they look very dark.

**Comment by xpirad** [comment]
What does 16 bit linear image mean? @guanyingc

**Comment by guanyingc** [comment]
In fact, the png image in the DiLiGenT dataset is 16 bit. But in this code, the read image in the dataloader is 8 bit as we use imageio library to read png.

**Comment by xpirad** [comment]
Thanks for your help!
Sorry that i'm not familiar with image processing. I didn't quite understand what you said.
Why is the image in 16 bit linear and what' the benefit of it? 
What does read image mean? It is 8bit ?? But isn't the image in 16bit?

**Comment by guanyingc** [comment]
1. 16 bit image can store more information. For example, 8bit image only has a range of 0-255, but a 16 bit image has a range of [0, 65535].
2. Although the original image is 16bit, the read image (i.e., the loaded image in numpy array format) in our dataloader is 8 bit. This means we treat the input images as 8bit images. You can use opencv to read 16bit png if you want. You may search on google to learn more difference between 16bit and 8bit images.

**Comment by xpirad** [comment]
I see, thank you guanying!

**Comment by xpirad** [comment]
Sorry for the trouble, guanyin. I have one more question.
So from my understanding, the difference between linear image and non-linear image are that the non-linear images are gamma adjusted, right?
So what gamma value should i use to adjust it? Will 2.6 be a fine value?
Your help will be deeply appreciated, thanks again!!!

**Comment by xpirad** [comment]
The images i'm getting from my camera seems to be non-linear ones.
So if i want to test them on SDPS-Net, i need to gamma adjust them, right?

**Comment by guanyingc** [comment]
Sorry for the super late reply.
You have to capture the raw data. You should no gamma adjust the images.

**Comment by xpirad** [comment]
@guanyingc  
Thanks for the reply!!
But the raw data i captured seems just normal, i mean, they are not as dark as the diligent dataset. They are just like normal picture...
How should i do?

**Comment by guanyingc** [comment]
1. You may not have captured the right raw data.
2. You may have to create the HDR image to remove the noise.
Please refer to the following figure for how the diligent dataset is captured (can be found its paper).
<img width="555" alt="Screen Shot 2020-11-20 at 5 14 37 PM" src="https://user-images.githubusercontent.com/8651158/99782414-1127cb80-2b54-11eb-9a8e-9a074fb24f71.png">

**Comment by xpirad** [comment]
I see, thank you guanying!
